### ISSUE TITLE
PDF missing image & Servo horn missing? 

### ISSUE THREAD

**Issue by davejavu1969** [junbowu/jrobot#1]
Hi, I've started to print this but am sadly finding problems.

Can you confirm standard SG90 9g servos will fit - they do not seem to? 

The stl for the servo horn is missing? - The link to the Plen library shows a cross-shape, this is not correct for the design of the slots as I see it? - Do you have the correct servo horn stl file? 

Would love to be able to build this completely! 
Many thanks,

DP.

**Comment by davejavu1969** [comment]
Ah - additionally, the images for the leg PDF are incomplete - do you have a full version? 

Thanks,

DP.

**Comment by junbowu** [comment]
1.servo : es08ma II or es08md ii
2.http://plen.jp/playground/wiki/tutorials/index.html
